const conversionToolsDb = [
  {
    id: 190,
    image: "images/keyword selection.svg",
    title: "Currency Conversion",
    category: "Conversion Tools",
    categorysty: "dec",
    type: "currencyConversion",
    link: "/conversiontools/currencyConversion",
    desc: "Convert Currencies",
  },
  {
    id: 91,
    image: "images/keyword selection.svg",
    title: "Temperature Conversion",
    category: "Conversion Tools",
    categorysty: "dec",
    type: "temperatureConversion",
    link: "/conversiontools/temperatureConversion",
    desc: "Convert temperatures",
  },
  {
    id: 92,
    image: "images/keyword selection.svg",
    title: "Presurre Conversion",
    category: "Conversion Tools",
    categorysty: "dec",
    type: "presurreConversion",
    link: "/conversiontools/presurreConversion",
    desc: "Convert Presurre units",
  },
  {
    id: 93,
    image: "images/keyword selection.svg",
    title: "Volume Conversion",
    category: "Conversion Tools",
    categorysty: "dec",
    type: "volumeConversion",
    link: "/conversiontools/volumeConversion",
    desc: "Convert Volume units",
  },
  {
    id: 94,
    image: "images/keyword selection.svg",
    title: "Area Conversion",
    category: "Conversion Tools",
    categorysty: "dec",
    type: "areaConversion",
    link: "/conversiontools/areaConversion",
    desc: "Convert Volume units",
  },
  {
    id: 95,
    image: "images/keyword selection.svg",
    title: "Time Conversion",
    category: "Conversion Tools",
    categorysty: "dec",
    type: "timeConversion",
    link: "/conversiontools/timeConversion",
    desc: "Convert Time from hours to minutes to seconds",
  },
  {
    id: 96,
    image: "images/keyword selection.svg",
    title: "Mass Conversion",
    category: "Conversion Tools",
    categorysty: "dec",
    type: "massConversion",
    link: "/conversiontools/massConversion",
    desc: "Convert Mass Units",
  },
  {
    id: 97,
    image: "images/keyword selection.svg",
    title: "Power Conversion",
    category: "Conversion Tools",
    categorysty: "dec",
    type: "powerConversion",
    link: "/conversiontools/powerConversion",
    desc: "Convert Power Units",
  },
  {
    id: 98,
    image: "images/keyword selection.svg",
    title: "Length Conversion",
    category: "Conversion Tools",
    categorysty: "dec",
    type: "lengthConversion",
    link: "/conversiontools/lengthConversion",
    desc: "Convert Length Units",
  },
  {
    id: 99,
    image: "images/keyword selection.svg",
    title: "Speed Conversion",
    category: "Conversion Tools",
    categorysty: "dec",
    type: "speedConversion",
    link: "/conversiontools/speedConversion",
    desc: "Convert speed Units",
  },
  {
    id: 100,
    image: "images/keyword selection.svg",
    title: "Fuel Economy Conversion",
    category: "Conversion Tools",
    categorysty: "dec",
    type: "fuelEconomyConversion",
    link: "/conversiontools/fuelEconomyConversion",
    desc: "Analyse your Fuel Economy",
  },
  {
    id: 101,
    image: "images/keyword selection.svg",
    title: "Energy Conversion",
    category: "Conversion Tools",
    categorysty: "dec",
    type: "energyConversion",
    link: "/conversiontools/energyConversion",
    desc: "Convert Energy Units",
  },
  {
    id: 102,
    image: "images/keyword selection.svg",
    title: "Plane Angle Conversion",
    category: "Conversion Tools",
    categorysty: "dec",
    type: "planeAngleConversion",
    link: "/conversiontools/planeAngleConversion",
    desc: "Convert Angles",
  },

  {
    id: 103,
    image: "images/keyword selection.svg",
    title: "Bit Byte Conversion",
    category: "Conversion Tools",
    categorysty: "dec",
    type: "bitByteConversion",
    link: "/conversiontools/bitByteConversion",
    desc: "Convert BitBytes",
  },
];

export default conversionToolsDb;
