import { v4 as uuidv4 } from 'uuid';
const CssTool = [
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Minify Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/MinifyCSS',
    desc: 'Generate CSS Minify with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Formatter Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/CSSformatter',
    desc: 'Generate CSS Formatter with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Box Shadow Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/box-shadow',
    desc: 'Generate Box Shadow with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/card-icon-21.png',
    title: 'CSS Gradient Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/gradientgenrator',
    desc: 'Generate CSS gradient with our CSS generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Text Shadow Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/text-shadow',
    desc: 'Generate Text Shadow with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Columns Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-column',
    desc: 'Generate Columns with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Display Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/display-gen',
    desc: 'Generate CSS display with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Visibility Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/visibilty-gen',
    desc: 'Generate CSS Visibility with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Border Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/border-gen',
    desc: 'Generate CSS Border with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Border Radius Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/border-radius-gen',
    desc: 'Generate CSS border radius with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Transform Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-transform-gen',
    desc: 'Generate CSS Transform with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Border Image Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-borderimg-gen',
    desc: 'Generate CSS Border Image with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Box Resize Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-boxresize-gen',
    desc: 'Generate CSS box resize with our CSS generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Opacity Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-opacity-gen',
    desc: 'Generate CSS Opacity with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Outline Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-outline-gen',
    desc: 'Generate CSS outline with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Overflow Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-overflow-gen',
    desc: 'Generate CSS Overflow with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Background Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-background-gen',
    desc: 'Generate CSS Background with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Text Color Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-textcolor-gen',
    desc: 'Generate CSS text color with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Blur Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-blur-gen',
    desc: 'Generate CSS Blur with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Brightness Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-brightness-gen',
    desc: 'Generate CSS brightness with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Contrast Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-contrast-gen',
    desc: 'Generate CSS Contrast with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Grayscale Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-grayscale-gen',
    desc: 'Generate CSS Grayscale with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Hue Rotate Generator ',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-hue-rotate-gen',
    desc: 'Generate CSS Hue Rotate with our CSS generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Invert Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-invert-gen',
    desc: 'Generate CSS Invert with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Saturate Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-saturate-gen',
    desc: 'Generate CSS Saturate with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Sepia Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-sepia-gen',
    desc: 'Generate CSS Sepia with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS List Style Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-liststyle-gen',
    desc: 'Generate CSS List Style with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Cursor Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-cursor-gen',
    desc: 'Generate CSS Cursor with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Letter Spacing Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-letter-spacing-gen',
    desc: 'Generate CSS Letter Spacing with our generator tool.',
  },

  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Text Align Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-text-align-gen',
    desc: 'Generate CSS Align Text with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Text Decoration Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-text-decoration-gen',
    desc: 'Generate CSS Text Decoration with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Text Indent Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-text-indent-gen',
    desc: 'Generate CSS Indent with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Text Transform Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-text-transform-gen',
    desc: 'Generate CSS Transform with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS White Space Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-white-space-gen',
    desc: 'Generate CSS White Space with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Word Break Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-word-break-gen',
    desc: 'Generate CSS Word Break with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Word Spacing Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-word-spacing-gen',
    desc: 'Generate CSS Word Spacing with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Line Height Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-line-height-gen',
    desc: 'Generate CSS Line Height with our generator tool.',
  },
  {
    id: uuidv4(),
    image: 'images/css-file-format.png',
    title: 'CSS Overflow Wrap Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-overflow-wrap-gen',
    desc: 'Generate CSS Overflow wrap with our generator tool.',
  },
];
export default CssTool;
