const JsonTool = [
  {
    id: 1041,
    image: "images/json-file.png",
    title: "JSON Minify Generator",
    category: "JSON Tools", 
    categorysty: "dec",
    type: "",
    link: "/MinifyJSON",
    desc: "Generate JSON Minify with our generator tool.",
  },
  {
    id: 1042,
    image: "images/json-file.png",
    title: "JSON Formatter",
    category: "JSON Tools",
    categorysty: "dec",
    type: "",
    link: "/jsonformatter",
    desc: "Formate JSON Formatter with our  generator tool.",
  },
  {
    id: 1043,
    image: "images/json-file.png",
    title: "JSON Validator",
    category: "JSON Tools",
    categorysty: "dec",
    type: "",
    link: "/json-validator",
    desc: "Validate Json with our generator tool.",
  },
  {
    id: 1044,
    image: "images/json-file.png",
    title: "JSON To XML Generator",
    category: "JSON Tools",
    categorysty: "dec",
    type: "",
    link: "/json-to-xml",
    desc: "Generate JSON To XML with our generator tool.",
  },
  {
    id: 1045,
    image: "images/json-file.png",
    title: "XML To JSON Generator",
    category: "JSON Tools",
    categorysty: "dec",
    type: "",
    link: "/xml-to-json",
    desc: "Generate XML To JSON with our  generator tool.",
  },
  {
    id: 1046,
    image: "images/json-file.png",
    title: "JSON To YAML Generator",
    category: "JSON Tools",
    categorysty: "dec",
    type: "",
    link: "/json-to-yaml",
    desc: "Generate JSON To YAML with our generator tool.",
  },
  {
    id: 1047,
    image: "images/json-file.png",
    title: "JSON To Base64 Generator",
    category: "JSON Tools",
    categorysty: "dec",
    type: "",
    link: "/json-to-base64",
    desc: "Generate JSON To Base64 with our generator tool.",
  },
  {
    id: 1048,
    image: "images/json-file.png",
    title: "Base64 To JSON Generator",
    category: "JSON Tools",
    categorysty: "dec",
    type: "",
    link: "/base64-to-json",
    desc: "Generate Base64 To JSON with our generator tool.",
  },
  {
    id: 1049,
    image: "images/json-file.png",
    title: "JSON To Text Generator",
    category: "JSON Tools",
    categorysty: "dec",
    type: "",
    link: "/json-to-text",
    desc: "Generate JSON To Text with our generator tool.",
  },
  {
    id: 1050,
    image: "images/json-file.png",
    title: "JSON To CSV Generator",
    category: "JSON Tools",
    categorysty: "dec",
    type: "",
    link: "/json-to-csv",
    desc: "Generate JSON To CSV with our generator tool.",
  },
  {
    id: 1051,
    image: "images/json-file.png",
    title: "CSV To JSON Generator",
    category: "JSON Tools",
    categorysty: "dec",
    type: "",
    link: "/csv-to-json",
    desc: "Generate CSV To JSON with our generator tool.",
  },
  {
    id: 1052,
    image: "images/json-file.png",
    title: "TSV To JSON Generator",
    category: "JSON Tools",
    categorysty: "dec",
    type: "",
    link: "/tsv-to-json",
    desc: "Generate TSV To JSON with our generator tool.",
  },
  {
    id: 1053,
    image: "images/json-file.png",
    title: "JSON To TSV Generator",
    category: "JSON Tools",
    categorysty: "dec",
    type: "",
    link: "/json-to-tsv",
    desc: "Generate JSON To TSV with our generator tool.",
  },
];
export default JsonTool;
